version: "2"

checks:
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 8

plugins:
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 50
  fixme:
    enabled: true

exclude_patterns:
- "**/tests/"
- "**/migrations/"
- "**/fixtures/"