version: "2"

checks:
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 8
  similar-code:
    config:
      threshold: 40
  identical-code:
    config:
      threshold: 40

plugins:
  pep8:
    enabled: true

exclude_patterns:
- "**/tests/"
- "**/migrations/"
- "**/fixtures/"