version: "2"

checks:
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 8
  similar-code:
    config:
      languages:
        python:
          mass_threshold: 50
  identical-code:
    config:
      languages:
        python:
          mass_threshold: 50

plugins:
  pep8:
    enabled: true

exclude_patterns:
- "**/tests/"
- "**/migrations/"
- "**/fixtures/"