language: python
python: "3.4.5"

before_install: "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install: "pip install -r requirements.txt"

before_script:
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  - sleep 3

script: "python3 manage.py compilemessages && python3 manage.py test"

notifications:
  slack: osisteam:2M3DtIOGE4clU1DF8r6k8NQD
services:
  - postgresql
  - rabbitmq
addons:
    postgresql: "9.4"
    firefox: "44.0"
after_sucess:
    - CODECLIMATE_REPO_TOKEN=37a30b73c9ca86e79442503327038e6b7fe540d4cdeec8ecde1bfe9a43e19d9a codeclimate-test-reporter