language: python
python: "3.4.5"
install: "pip install -r requirements.txt"
addons:
  firefox: "46.0"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
script: "python3 manage.py compilemessages && phantomjs base/tests/functional/test_learning_units.py"

./manage.py test animals/

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install connect
  - sudo node test/js/server.js ../../ 80 &
  - sleep 5
script:  "http://localhost:80/test/index.html"




notifications:
  slack: osisteam:2M3DtIOGE4clU1DF8r6k8NQD
services:
  - postgresql
  - rabbitmq
addons:
    postgresql: "9.4"
after_sucess:
    - CODECLIMATE_REPO_TOKEN=37a30b73c9ca86e79442503327038e6b7fe540d4cdeec8ecde1bfe9a43e19d9a codeclimate-test-reporter