language: python
python: "3.4.5"

before_install:
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz"
  - "mkdir geckodriver"
  - "tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver"
  - "export PATH=$PATH:$PWD/geckodriver"

addons:
    firefox: "latest-nightly"
    selenium: "3.3.1"

install:
  - "pip install -r requirements.txt"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"

script: "python3 manage.py compilemessages && python3 manage.py test"

notifications:
  slack: osisteam:2M3DtIOGE4clU1DF8r6k8NQD
services:
  - postgresql
  - rabbitmq
addons:
    postgresql: "9.4"
after_sucess:
    - CODECLIMATE_REPO_TOKEN=37a30b73c9ca86e79442503327038e6b7fe540d4cdeec8ecde1bfe9a43e19d9a codeclimate-test-reporter